### ISSUE TITLE
ERROR Error saving index on close()

### ISSUE THREAD

**Issue by markbasham** [boolsi/boolsi#1]
Hi,

Just playing with this, and everything works great, but when i try to run with mpi, i get a Error at the end for the first and last example, but the 2nd example is fine.

> Step 11/13 : RUN mpiexec -np 2 boolsi simulate examples/example1.yaml -t 5
>  ---> Running in 3e7ae15da9fa
> 05-Aug-2020 17:55:15 Hi! All BoolSi output (including this log) will appear in "/output_20200805T175515.292/".
> 05-Aug-2020 17:55:15 Run parameters: "simulate examples/example1.yaml -t 5".
> 05-Aug-2020 17:55:15 Initializing temporary storage in "/tmp_db/".
> 05-Aug-2020 17:55:15 Read Boolean network of 3 nodes.
> 05-Aug-2020 17:55:15 1 worker processes will be used to perform 2 simulations...
> 05-Aug-2020 17:55:15 Performing simulations... (see progressbar in "output_20200805T175515.292/progress.txt").
> 05-Aug-2020 17:55:15 Collecting results... (see progressbar in "output_20200805T175515.292/progress.txt").
> 05-Aug-2020 17:55:15 Preprocessing simulations for graphic output... (see progressbar in "output_20200805T175515.292/progress.txt").
> 05-Aug-2020 17:55:15 Printing simulations to "simulations.pdf", "simulation_summaries.csv/", and "simulations.csv/"... (see progressbar in "output_20200805T175515.292/progress.txt").
> 05-Aug-2020 17:55:16 Terminating...
> 05-Aug-2020 17:55:16 ERROR Error saving index on close()
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/FileStorage/FileStorage.py", line 511, in close
>     self._save_index()
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/FileStorage/FileStorage.py", line 368, in _save_index
>     self._index.save(self._pos, tmp_name)
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/fsIndex.py", line 112, in save
>     with open(fname, 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'tmp_db/simulation_results_20200805175515293981_0.index.index_tmp'
> 05-Aug-2020 17:55:16 All BoolSi output is located in "/output_20200805T175515.292/". Bye!
> Removing intermediate container 3e7ae15da9fa
>  ---> d8da288157ba
> Step 12/13 : RUN mpiexec -np 2 boolsi attract examples/example2.yaml
>  ---> Running in 409794fde0d0
> 05-Aug-2020 17:55:18 Hi! All BoolSi output (including this log) will appear in "/output_20200805T175518.608/".
> 05-Aug-2020 17:55:18 Run parameters: "attract examples/example2.yaml".
> 05-Aug-2020 17:55:18 Initializing temporary storage in "/tmp_db/".
> 05-Aug-2020 17:55:18 Read Boolean network of 3 nodes.
> 05-Aug-2020 17:55:18 1 worker processes will be used to find attractors from 8 initial conditions...
> 05-Aug-2020 17:55:18 Performing simulations... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:18 Collecting results... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:18 Found 2 attractors.
> 05-Aug-2020 17:55:18 Sorting attractors... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:18 Restructuring attractors... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:18 Reading attractors to compute node correlations... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:18 Computing node correlations...
> 05-Aug-2020 17:55:18 Printing node correlations to "node_correlations.pdf" and "node_correlations.csv"...
> 05-Aug-2020 17:55:19 Preprocessing attractors for graphic output... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:19 Printing attractors to "attractors.pdf", "attractor_summaries.csv/", and "attractors.csv/"... (see progressbar in "output_20200805T175518.608/progress.txt").
> 05-Aug-2020 17:55:20 Terminating...
> 05-Aug-2020 17:55:20 All BoolSi output is located in "/output_20200805T175518.608/". Bye!
> Removing intermediate container 409794fde0d0
>  ---> c2bf3761a2a5
> Step 13/13 : RUN mpiexec -np 2 boolsi target examples/example3.yaml
>  ---> Running in e7f5e15af5a2
> 05-Aug-2020 17:55:22 Hi! All BoolSi output (including this log) will appear in "/output_20200805T175522.388/".
> 05-Aug-2020 17:55:22 Run parameters: "target examples/example3.yaml".
> 05-Aug-2020 17:55:22 Initializing temporary storage in "/tmp_db/".
> 05-Aug-2020 17:55:22 Read Boolean network of 3 nodes.
> 05-Aug-2020 17:55:22 1 worker processes will be used to perform 4 simulations and find all that reach target states.
> 05-Aug-2020 17:55:22 Performing simulations... (see progressbar in "output_20200805T175522.388/progress.txt").
> 05-Aug-2020 17:55:22 Collecting results... (see progressbar in "output_20200805T175522.388/progress.txt").
> 05-Aug-2020 17:55:22 Only 1 simulations reach target state.
> 05-Aug-2020 17:55:22 Preprocessing simulations for graphic output... (see progressbar in "output_20200805T175522.388/progress.txt").
> 05-Aug-2020 17:55:22 Printing simulations to "simulations.pdf", "simulation_summaries.csv/", and "simulations.csv/"... (see progressbar in "output_20200805T175522.388/progress.txt").
> 05-Aug-2020 17:55:23 Terminating...
> 05-Aug-2020 17:55:23 ERROR Error saving index on close()
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/FileStorage/FileStorage.py", line 511, in close
>     self._save_index()
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/FileStorage/FileStorage.py", line 368, in _save_index
>     self._index.save(self._pos, tmp_name)
>   File "/opt/conda/lib/python3.7/site-packages/ZODB/fsIndex.py", line 112, in save
>     with open(fname, 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'tmp_db/simulation_results_20200805175522390309_0.index.index_tmp'
> 05-Aug-2020 17:55:23 All BoolSi output is located in "/output_20200805T175522.388/". Bye!

I will put a pull request in for the Docker container I built to test this out as you might find it useful.

Cheers

Mark

**Comment by markbasham** [comment]
you can see everythign here [Dockerhub Build](https://hub.docker.com/repository/registry-1.docker.io/markbasham/boolsi/builds/8b1e24aa-1965-4bbe-835c-55bf2344a299)

**Comment by markbasham** [comment]
Just thought that if you want an easy way to look at the system, if you have docker installed anywhere or access to it, simmply run
`docker run -it markbasham/boolsi:latest /bin/bash`
then you will be on the command line in the container, where you can look at the outputs or just run the commands direclty to see whats wrong, i.e. 
`boolsi simulate examples/example1.yaml -t 5`
or 
`mpirun -np 2 boolsi simulate examples/example1.yaml -t 5`
for example

**Comment by vlad-oles** [comment]
Thanks so much for pointing out the issue!

Apparently it was caused by race condition — temporary DB directory was getting deleted by the master before the worker was done cleaning it up. Just released version 1.0.3 with the DB directory not getting removed upon completion, which fixes the issue.

**Comment by kukushking** [comment]
Thanks so much for pointing this out!

Apparently there was a race condition with temporary DB directory being removed by the master while still in use by the worker. It was only happening during the cleanup though and didn't affect the functionality.

Just released version 1.0.3 with the fix.
